//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporSalonuOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class testTablo
    {
        public int ID { get; set; }
        public string KimlikNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Telefon { get; set; }
        public string AylikBilgisi { get; set; }
        public Nullable<System.DateTime> UyeOlunanTarih { get; set; }
        public Nullable<System.DateTime> UyelikBitisTarihi { get; set; }
        public string UyeDurumu { get; set; }
        public string Aciklama { get; set; }
    }
}
